/*
# Add referral system to app_users

## Purpose
Gives every user a unique, shareable invitation code. When someone
registers using another person's code, the link is recorded. This
powers the Rewards / referral page.

## Modified Tables
- `app_users`
  - New column: `referral_code` (text, unique) — auto-generated
    8-character uppercase alphanumeric code, e.g. "X7K2QM9P".
    Generated by a BEFORE INSERT trigger; cannot be NULL after insert.
  - New column: `referred_by` (text, nullable) — stores the
    `referral_code` of the person who invited this user.

## Security
No new RLS policies needed. The existing anon SELECT / INSERT / UPDATE
policies cover these new columns.

## Notes
1. `generate_referral_code()` loops until it finds a value that does
   not already exist in the table — collision-safe.
2. `referred_by` is nullable; users who registered without a code have NULL.
3. Existing users get a unique referral_code automatically via the
   DO block that runs during the migration.
*/

-- 1. Helper function to create a unique 8-char code
CREATE OR REPLACE FUNCTION generate_referral_code()
RETURNS TEXT AS $$
DECLARE
  chars TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  code  TEXT := '';
  i     INT;
  taken BOOLEAN;
BEGIN
  LOOP
    code := '';
    FOR i IN 1..8 LOOP
      code := code || substr(chars, floor(random() * 36 + 1)::INT, 1);
    END LOOP;
    SELECT EXISTS(SELECT 1 FROM app_users WHERE referral_code = code) INTO taken;
    EXIT WHEN NOT taken;
  END LOOP;
  RETURN code;
END;
$$ LANGUAGE plpgsql;

-- 2. Add columns (idempotent)
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS referral_code TEXT;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS referred_by   TEXT;

-- 3. Generate codes for all existing users that don't have one yet
DO $$
DECLARE rec RECORD;
BEGIN
  FOR rec IN SELECT id FROM app_users WHERE referral_code IS NULL LOOP
    UPDATE app_users SET referral_code = generate_referral_code() WHERE id = rec.id;
  END LOOP;
END $$;

-- 4. Add unique constraint (idempotent via DO block)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'app_users_referral_code_key'
  ) THEN
    ALTER TABLE app_users ADD CONSTRAINT app_users_referral_code_key UNIQUE (referral_code);
  END IF;
END $$;

-- 5. Trigger: auto-assign a referral_code on every new INSERT
CREATE OR REPLACE FUNCTION trg_set_referral_code()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.referral_code IS NULL THEN
    NEW.referral_code := generate_referral_code();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_referral_code ON app_users;
CREATE TRIGGER set_referral_code
  BEFORE INSERT ON app_users
  FOR EACH ROW EXECUTE FUNCTION trg_set_referral_code();
